### ISSUE TITLE
Kindly add bitcoingold masternode.

### ISSUE THREAD

**Issue by qasimsaleem1** [BTCGPU/Developer-Portal#8]
We are waiting for bitcoingold masternode. With the help of masternode 60% coin will be locked up in wallet like dash and other coins.
Which will really help to attract users and help to increase adoption.

**Comment by MentalNomad** [comment]
Creating masternodes _in order to "lock up coins"_ would do nothing to attract users or increase adoption. It's just a scheme to pay people to hold coins in hopes of creating some sort of rising price sprial. That's neither usage nor adoption - it's gambling on on masternodes. It's just artificial reduction of coin supply done _at the expense of decentralization_ - and improving decentralization is the _primary purpose_ of the BTG project.

You've repeatedly proposed, in several BTG social channels, that masternodes would "lock up coins," leading to an increase in price. To me, doing such a thing would be fraudulent and I would never be in favor. Kindly stop proposing something which is _antithetical to the core purpose of the project_.
